### ISSUE TITLE
Maven repository

### ISSUE THREAD

**Issue by sgdc3** [Yamakaja/RuntimeTransformer#5]
I added the project to my jenkins + auto deploy to maven repository:

https://ci.codemc.org/view/Yamakaja/job/RuntimeTransformer/
https://repo.codemc.org/repository/maven-public/

You can login to jenkins with the github oauth and change the project settings as you want ;)

**Comment by sgdc3** [comment]
We also have a discord server if you need support: https://discord.gg/AGcFMu6

**Comment by Yamakaja** [comment]
Added note to readme
